const translations = {
  "ms": {
    "notice": "Laman ini ialah platform pendidikan dan pembangunan jenama. Produk yang dipaparkan belum ditawarkan untuk jualan sehingga status regulatori disahkan.",
    "navHome": "Utama",
    "navStory": "Kisah Kami",
    "navProducts": "Produk",
    "navLearn": "Belajar",
    "navRoadmap": "Langkah Kami",
    "navContact": "Hubungi",
    "eyebrow": "TGPU NATURALS",
    "heroTitle": "Kesejahteraan Semula Jadi,\nBerakar pada Warisan Keluarga",
    "heroLead": "TGPU Legacy meneroka kesejahteraan semula jadi melalui tiga konsep bahan tradisional. Kami berkongsi maklumat yang ringkas dan mudah difahami agar komuniti dapat belajar dan membuat pilihan bermaklumat.",
    "heroLearn": "Kenali Bahan",
    "heroRoadmap": "Lihat Perjalanan Kami",
    "trust1": "Diilhamkan\noleh alam",
    "trust2": "Dibina atas\nnilai keluarga",
    "trust3": "Bersama menuju\nmasa depan cerah",
    "sameRoots": "Akar yang Sama,",
    "strongerGen": "Generasi Lebih Teguh",
    "heritageText": "TGPU Legacy dibina daripada nilai keluarga, ilmu, amanah dan usaha untuk meninggalkan sesuatu yang bermanfaat kepada generasi seterusnya.",
    "familyValues": "Keluarga • Ilmu • Alam • Amanah",
    "storyEyebrow": "KISAH KAMI",
    "storyTitle": "Warisan Keluarga\ndalam Setiap Langkah",
    "storyP1": "TGPU Legacy diilhamkan oleh nilai keluarga, warisan dan penghargaan terhadap alam. Kami meneroka kesejahteraan semula jadi, dibina selangkah demi selangkah dengan teliti dan ikhlas, sambil berkongsi maklumat bahan yang jelas untuk komuniti.",
    "storyP2": "TGPU bermaksud Tok Guru Pulau Ubi. Pendidikan kekal sebagai teras warisan keluarga kami.",
    "educationLink": "Lawati laman pendidikan TGPU Legacy →",
    "productsEyebrow": "PRODUK KAMI",
    "productsTitle": "TGPU Naturals",
    "productsIntro": "Visual Kunyit Hitam dan Sacha Inchi diperkemas berdasarkan pembungkusan sebenar keluarga kami. Tongkat Ali masih menggunakan visual konsep sementara menunggu foto sebenar. Maklumat label, formulasi dan status produk masih dalam pengesahan; laman ini untuk pertanyaan buat masa ini.",
    "actualVisualBadge": "VISUAL DIPERKEMAS DARIPADA PRODUK SEBENAR",
    "conceptBadge": "PEMBUNGKUSAN KONSEP",
    "kunyitTitle": "Kunyit Hitam",
    "kunyitDesc": "Rizom tradisional yang dikenali dengan warna dalamnya yang gelap dan tempatnya dalam tradisi herba tempatan.",
    "tongkatTitle": "Tongkat Ali",
    "tongkatDesc": "Tumbuhan Asia Tenggara yang telah lama dikenali dalam budaya herba serantau.",
    "sachiTitle": "Sacha Inchi",
    "sachiBotanical": "Plukenetia volubilis",
    "sachiDesc": "Tumbuhan berbiji dari kawasan tropika Amerika Selatan, diperkenalkan dalam perjalanan keluarga kami mengenali bahan semula jadi.",
    "learnIngredient": "Baca penerangan umum →",
    "learnEyebrow": "BELAJAR DENGAN TGPU",
    "learnTitle": "Kenali bahan sebelum mengenali produk.",
    "learnIntro": "Kami memisahkan pengetahuan umum daripada promosi produk. Tujuannya ialah membantu pembaca memahami asal-usul dan identiti bahan dengan lebih jelas.",
    "whatKunyit": "Apakah Kunyit Hitam?",
    "whatKunyitText": "Kunyit Hitam ialah tumbuhan rizom daripada genus Curcuma. Nama saintifik yang sering dikaitkan dengannya ialah Curcuma caesia. Spesies dan bahan sebenar perlu disahkan pada peringkat sumber dan formulasi.",
    "whatTongkat": "Apakah Tongkat Ali?",
    "whatTongkatText": "Tongkat Ali ialah Eurycoma longifolia, tumbuhan Asia Tenggara yang terkenal dalam budaya herba tempatan. Sejarah penggunaan tradisional tidak sama dengan bukti klinikal untuk sesuatu produk tertentu.",
    "whatSachi": "Apakah Sacha Inchi?",
    "whatSachiText": "Sacha Inchi ialah Plukenetia volubilis, tumbuhan tropika dari Amerika Selatan yang menghasilkan biji. Cara sesuatu produk diklasifikasikan bergantung pada bentuk, formulasi, ramuan dan cara ia dipasarkan.",
    "important": "Nota penting",
    "medicalDisclaimer": "Kandungan ini untuk tujuan pendidikan dan maklumat umum sahaja. Ia bukan nasihat perubatan, diagnosis atau rawatan, dan tidak menyatakan bahawa mana-mana produk boleh mencegah, merawat atau menyembuhkan penyakit.",
    "roadmapEyebrow": "MULA KECIL, BINA BETUL",
    "roadmapTitle": "Perjalanan TGPU Naturals.",
    "step1Title": "Identiti & laman pendidikan",
    "step1Text": "Bina jenama, kisah keluarga, struktur maklumat dan saluran komunikasi.",
    "step2Title": "Sahkan produk sebenar",
    "step2Text": "Kumpul foto, formulasi, ramuan, pengilang, label dan butiran bekalan sebenar daripada keluarga.",
    "step3Title": "Klasifikasi & keperluan regulatori",
    "step3Text": "Tentukan kategori setiap produk dan lengkapkan pendaftaran/kelulusan yang diperlukan sebelum jualan.",
    "step4Title": "SSM & operasi",
    "step4Text": "Tetapkan entiti perniagaan, akaun, pembekal, polisi pelanggan dan rekod operasi yang sesuai.",
    "step5Title": "Pelancaran rasmi",
    "step5Text": "Gantikan visual konsep dengan produk sebenar dan aktifkan fungsi jualan hanya selepas semua perkara utama disahkan.",
    "statusEyebrow": "STATUS SEMASA",
    "statusTitle": "Belum ditawarkan untuk jualan.",
    "statusText": "TGPU Naturals sedang berada pada peringkat pembangunan. Produk konsep di laman ini tidak mewakili pembungkusan akhir dan belum dipaparkan sebagai produk berdaftar. Kami akan mengemas kini maklumat hanya selepas status produk, klasifikasi dan dokumen berkaitan disahkan.",
    "faqTitle": "Soalan yang mungkin keluarga & pelanggan tanya.",
    "faq1q": "Boleh saya membuat pesanan sekarang?",
    "faq1a": "Belum melalui laman ini. Kami sedang menyusun semula produk dan mengesahkan keperluan regulatori terlebih dahulu.",
    "faq2q": "Adakah gambar produk ini gambar sebenar?",
    "faq2a": "Tidak. Ia ialah visual konsep untuk membantu keluarga kami membayangkan arah jenama. Gambar sebenar akan menggantikannya kemudian.",
    "faq3q": "Adakah TGPU Naturals memberi nasihat perubatan?",
    "faq3a": "Tidak. Kandungan laman ini bersifat pendidikan umum dan tidak menggantikan nasihat profesional kesihatan.",
    "faq4q": "Bagaimana saya boleh mengikuti perkembangan?",
    "faq4a": "Hubungi kami melalui WhatsApp dan nyatakan bahawa anda mahu menerima perkembangan TGPU Naturals.",
    "contactEyebrow": "BERKEMBANG BERSAMA",
    "contactTitle": "Pertanyaan Produk / Hubungi Kami",
    "contactText": "Untuk maklumat dan pertanyaan sahaja. Produk belum ditawarkan untuk jualan.",
    "contactBtn": "WhatsApp MOE",
    "contactPerson": "Pegawai pertanyaan produk: MOE",
    "footerText": "Insan · Alam · Keluarga · Masa Depan Lebih Cerah",
    "educationShort": "Pendidikan",
    "heroSignature": "Keluarga Bahagia,\nEsok Lebih Bermakna",
    "brandTagline": "NILAI KELUARGA · KESEJAHTERAAN SEMULA JADI · MASA DEPAN CERAH",
    "productsSubtitle": "Bahan Tradisional untuk Perjalanan Kesejahteraan Hari Ini",
    "storySignature": "Langkah Kecil,\nManfaat Berpanjangan",
    "heritageSignature": "Warisan Kita,\nKeluarga Kita,\nMasa Depan Kita",
    "footerSignature": "Kesejahteraan Hari Ini,\nKeluarga Lebih Teguh Esok",
    "learnSummary": "Panduan bahan, perjalanan kami & soalan",
    "menuOpen": "Buka navigasi",
    "menuClose": "Tutup navigasi",
    "switchLabel": "Terokai TGPU Legacy",
    "skip": "Terus ke kandungan",
    "sourceLabel": "Rujukan botani: Kew Science",
    "artNote": "Gambaran keluarga dan warisan bersifat ilustrasi. Visual Kunyit Hitam dan Sacha Inchi diperkemas daripada pembungkusan sebenar; Tongkat Ali masih visual konsep.",
    "copyright": "TGPU Legacy · TGPU Naturals",
    "metaDescription": "Kenali TGPU Naturals: warisan keluarga dan maklumat jelas tentang Kunyit Hitam, Tongkat Ali dan Sacha Inchi. Pembungkusan konsep; pertanyaan sahaja.",
    "heroAlt": "Ilustrasi keluarga Melayu menikmati pemandangan gunung berkabus dari beranda kayu.",
    "kunyitAlt": "Visual produk Kunyit Hitam yang diperkemas berdasarkan botol dan pembungkusan sebenar.",
    "tongkatAlt": "Konsep botol Tongkat Ali TGPU Naturals hijau bertutup emas dengan akar dan daun.",
    "sachiAlt": "Visual produk Sacha Inchi yang diperkemas berdasarkan botol dan pembungkusan sebenar."
  },
  "en": {
    "notice": "This is an educational and brand-development platform. The displayed product concepts are not offered for sale until their regulatory status is confirmed.",
    "navHome": "Home",
    "navStory": "Our Story",
    "navProducts": "Products",
    "navLearn": "Learn",
    "navRoadmap": "Our Roadmap",
    "navContact": "Contact",
    "eyebrow": "TGPU NATURALS",
    "heroTitle": "Natural Wellness\nRooted in Family Legacy",
    "heroLead": "TGPU Legacy is exploring natural wellness through three traditional ingredient concepts. We share simple, easy-to-understand information, so our community can learn and make informed choices.",
    "heroLearn": "Explore Ingredients",
    "heroRoadmap": "See Our Journey",
    "trust1": "Inspired\nby nature",
    "trust2": "Built on\nfamily values",
    "trust3": "Together for\na brighter tomorrow",
    "sameRoots": "Same Roots,",
    "strongerGen": "Stronger Generations",
    "heritageText": "TGPU Legacy is built on family values, knowledge, trust and the aim of leaving something beneficial for the next generation.",
    "familyValues": "Family • Knowledge • Nature • Trust",
    "storyEyebrow": "OUR STORY",
    "storyTitle": "A Family Legacy\nin Every Step",
    "storyP1": "TGPU Legacy is inspired by our family values, our heritage, and an appreciation of nature. We are exploring natural wellness, built step by step with care and sincerity, and sharing clear ingredient information with our community.",
    "storyP2": "TGPU stands for Tok Guru Pulau Ubi. Education remains at the heart of our family’s legacy.",
    "educationLink": "Visit the TGPU Legacy education website →",
    "productsEyebrow": "OUR PRODUCTS",
    "productsTitle": "TGPU Naturals",
    "productsIntro": "Kunyit Hitam and Sacha Inchi visuals have been polished from our family’s actual packaging. Tongkat Ali still uses a temporary concept visual while we wait for the real product photo. Label, formulation and regulatory details are still being verified; this site is for enquiries at this stage.",
    "actualVisualBadge": "POLISHED FROM ACTUAL PRODUCT PACKAGING",
    "conceptBadge": "CONCEPT PACKAGING",
    "kunyitTitle": "Kunyit Hitam",
    "kunyitDesc": "A traditional rhizome known for its deep, dark colour and its place in local herbal traditions.",
    "tongkatTitle": "Tongkat Ali",
    "tongkatDesc": "A Southeast Asian botanical with a long history in the region’s herbal culture.",
    "sachiTitle": "Sacha Inchi",
    "sachiBotanical": "Plukenetia volubilis",
    "sachiDesc": "A seed-bearing plant from tropical South America, explored here as part of our family’s ingredient journey.",
    "learnIngredient": "Read the general guide →",
    "learnEyebrow": "LEARN WITH TGPU",
    "learnTitle": "Know the ingredient before the product.",
    "learnIntro": "We separate general knowledge from product promotion. Our aim is to help readers understand the origins and identity of each ingredient more clearly.",
    "whatKunyit": "What is Kunyit Hitam?",
    "whatKunyitText": "Black turmeric is a rhizomatous plant from the Curcuma genus. Curcuma caesia is a scientific name commonly associated with it. The exact species and material must be verified at sourcing and formulation stage.",
    "whatTongkat": "What is Tongkat Ali?",
    "whatTongkatText": "Tongkat Ali is Eurycoma longifolia, a Southeast Asian plant well known in local herbal culture. Historical traditional use is not the same as clinical evidence for a particular product.",
    "whatSachi": "What is Sacha Inchi?",
    "whatSachiText": "Sacha Inchi is Plukenetia volubilis, a tropical South American plant that produces seeds. How a product is classified depends on its form, formulation, ingredients and how it is marketed.",
    "important": "Important note",
    "medicalDisclaimer": "This content is for education and general information only. It is not medical advice, diagnosis or treatment and does not claim that any product can prevent, treat or cure disease.",
    "roadmapEyebrow": "START SMALL, BUILD PROPERLY",
    "roadmapTitle": "The TGPU Naturals journey.",
    "step1Title": "Identity & education website",
    "step1Text": "Build the brand, family story, information structure and communication channel.",
    "step2Title": "Verify the real products",
    "step2Text": "Collect actual photos, formulation, ingredients, manufacturer, labels and supply details from the family.",
    "step3Title": "Classification & regulatory requirements",
    "step3Text": "Determine each product category and complete required registration or approvals before sale.",
    "step4Title": "SSM & operations",
    "step4Text": "Set up the appropriate business entity, account, suppliers, customer policies and operating records.",
    "step5Title": "Official launch",
    "step5Text": "Replace concept visuals with real products and activate sales only after the key requirements are confirmed.",
    "statusEyebrow": "CURRENT STATUS",
    "statusTitle": "Not yet offered for sale.",
    "statusText": "TGPU Naturals is currently in development. The concepts shown here do not represent final packaging and are not presented as registered products. Information will be updated only after product status, classification and related documentation are confirmed.",
    "faqTitle": "Questions family and future customers may ask.",
    "faq1q": "Can I place an order now?",
    "faq1a": "Not through this website yet. We are reorganising the products and confirming regulatory requirements first.",
    "faq2q": "Are these the real product photos?",
    "faq2a": "No. They are concept visuals to help our family explore the brand direction. Real images will replace them later.",
    "faq3q": "Does TGPU Naturals provide medical advice?",
    "faq3a": "No. The website provides general educational information and does not replace professional healthcare advice.",
    "faq4q": "How can I follow the progress?",
    "faq4a": "Contact us on WhatsApp and tell us you would like to receive TGPU Naturals updates.",
    "contactEyebrow": "GROW WITH US",
    "contactTitle": "Product Enquiries / Get in Touch",
    "contactText": "For information and enquiries only. Products are not yet offered for sale.",
    "contactBtn": "WhatsApp Jannati",
    "contactPerson": "Product enquiries: MOE",
    "footerText": "People · Nature · Family · A Brighter Tomorrow",
    "educationShort": "Education",
    "heroSignature": "Good Families,\nBrighter Tomorrows",
    "brandTagline": "FAMILY VALUES · NATURAL WELLNESS · A BRIGHTER TOMORROW",
    "productsSubtitle": "Traditional Ingredients for Today’s Wellness Journey",
    "storySignature": "Small Steps,\nLasting Impact",
    "heritageSignature": "Our Heritage,\nOur Family,\nOur Tomorrow",
    "footerSignature": "Wellness Today,\nStronger Families Tomorrow",
    "learnSummary": "Ingredient guide, our journey & questions",
    "menuOpen": "Open navigation",
    "menuClose": "Close navigation",
    "switchLabel": "Explore TGPU Legacy",
    "skip": "Skip to content",
    "sourceLabel": "Botanical reference: Kew Science",
    "artNote": "Family and heritage scenes are illustrative. Kunyit Hitam and Sacha Inchi visuals are polished from actual packaging; Tongkat Ali remains a concept visual.",
    "copyright": "TGPU Legacy · TGPU Naturals",
    "metaDescription": "Discover TGPU Naturals: family heritage and clear information about Kunyit Hitam, Tongkat Ali and Sacha Inchi. Concept packaging; enquiries only.",
    "heroAlt": "Illustrative Malay family looking over a misty mountain landscape from a wooden veranda.",
    "kunyitAlt": "Polished Kunyit Hitam product visual based on the family’s actual bottle and packaging.",
    "tongkatAlt": "Green TGPU Naturals Tongkat Ali concept bottle with a gold cap, roots and leaves.",
    "sachiAlt": "Polished Sacha Inchi product visual based on the family’s actual bottle and packaging."
  },
  "ar": {
    "notice": "هذه منصة تعليمية لتطوير العلامة. المنتجات التصورية المعروضة ليست مطروحة للبيع إلى أن يتم تأكيد وضعها التنظيمي.",
    "navHome": "الرئيسية",
    "navStory": "قصتنا",
    "navProducts": "المنتجات",
    "navLearn": "تعلّم",
    "navRoadmap": "خطتنا",
    "navContact": "تواصل",
    "eyebrow": "TGPU NATURALS",
    "heroTitle": "عافية من الطبيعة،\nجذورها إرث العائلة",
    "heroLead": "تستكشف TGPU Legacy العافية الطبيعية من خلال ثلاثة تصورات لمكونات تقليدية. نشارك معلومات بسيطة وواضحة، ليتمكن مجتمعنا من التعلم واتخاذ خيارات واعية.",
    "heroLearn": "تعرّف على المكونات",
    "heroRoadmap": "شاهد رحلتنا",
    "trust1": "إلهام\nمن الطبيعة",
    "trust2": "على أساس\nقيم العائلة",
    "trust3": "معاً نحو\nغد أكثر إشراقاً",
    "sameRoots": "الجذور نفسها،",
    "strongerGen": "وأجيال أكثر تماسكاً",
    "heritageText": "تقوم TGPU Legacy على قيم العائلة والعلم والأمانة والرغبة في ترك أثر نافع للأجيال القادمة.",
    "familyValues": "العائلة • العلم • الطبيعة • الأمانة",
    "storyEyebrow": "قصتنا",
    "storyTitle": "إرث عائلي\nفي كل خطوة",
    "storyP1": "تستلهم TGPU Legacy قيم عائلتنا وإرثها وتقديرها للطبيعة. نستكشف العافية الطبيعية خطوة بخطوة بعناية وإخلاص، ونشارك معلومات واضحة عن المكونات مع مجتمعنا.",
    "storyP2": "يرمز TGPU إلى Tok Guru Pulau Ubi. ويبقى التعليم في قلب إرث عائلتنا.",
    "educationLink": "زيارة موقع TGPU Legacy التعليمي ←",
    "productsEyebrow": "منتجاتنا",
    "productsTitle": "TGPU Naturals",
    "productsIntro": "تم تحسين صور الكركم الأسود وساشا إنشي استناداً إلى العبوات الفعلية لدى العائلة، بينما لا تزال صورة تونغكات علي تصوراً مؤقتاً إلى حين وصول صورة المنتج الحقيقي. لا تزال بيانات الملصق والتركيبة والوضع التنظيمي قيد التحقق، والموقع مخصص للاستفسارات حالياً.",
    "actualVisualBadge": "صورة مُحسّنة استناداً إلى المنتج الفعلي",
    "conceptBadge": "تصور مبدئي للعبوة",
    "kunyitTitle": "الكركم الأسود",
    "kunyitDesc": "نبات جذموري تقليدي يُعرف بلونه الداخلي الداكن ومكانته في الثقافة العشبية المحلية.",
    "tongkatTitle": "تونغكات علي",
    "tongkatDesc": "نبات من جنوب شرق آسيا له حضور قديم في الثقافة العشبية بالمنطقة.",
    "sachiTitle": "ساشا إنشي",
    "sachiBotanical": "Plukenetia volubilis",
    "sachiDesc": "نبات ينتج بذوراً من المناطق الاستوائية في أمريكا الجنوبية، نتعرف عليه ضمن رحلة عائلتنا مع المكونات الطبيعية.",
    "learnIngredient": "اقرأ الدليل العام ←",
    "learnEyebrow": "تعلّم مع TGPU",
    "learnTitle": "تعرّف على المكوّن قبل المنتج.",
    "learnIntro": "نفصل المعرفة العامة عن الترويج للمنتجات، بهدف مساعدة القارئ على فهم أصل كل مكوّن وهويته بصورة أوضح.",
    "whatKunyit": "ما الكركم الأسود؟",
    "whatKunyitText": "الكركم الأسود نبات جذموري من جنس Curcuma، ويرتبط به غالباً الاسم العلمي Curcuma caesia. ويجب التحقق من النوع والمادة الفعلية في مرحلة التوريد والتركيب.",
    "whatTongkat": "ما تونغكات علي؟",
    "whatTongkatText": "تونغكات علي هو Eurycoma longifolia، نبات من جنوب شرق آسيا معروف في الثقافة العشبية المحلية. ولا يساوي الاستخدام التقليدي التاريخي دليلاً سريرياً على منتج بعينه.",
    "whatSachi": "ما ساشا إنشي؟",
    "whatSachiText": "ساشا إنشي هو Plukenetia volubilis، نبات استوائي من أمريكا الجنوبية ينتج بذوراً. ويتوقف تصنيف أي منتج على شكله وتركيبته ومكوناته وطريقة تسويقه.",
    "important": "ملاحظة مهمة",
    "medicalDisclaimer": "هذا المحتوى لأغراض التعليم والمعلومات العامة فقط. ولا يمثل نصيحة أو تشخيصاً أو علاجاً طبياً، ولا يدعي أن أي منتج يمنع المرض أو يعالجه أو يشفيه.",
    "roadmapEyebrow": "نبدأ صغيراً ونبني بصورة صحيحة",
    "roadmapTitle": "رحلة TGPU Naturals.",
    "step1Title": "الهوية والموقع التعليمي",
    "step1Text": "بناء العلامة وقصة العائلة وهيكل المعلومات وقناة التواصل.",
    "step2Title": "التحقق من المنتجات الفعلية",
    "step2Text": "جمع الصور الحقيقية والتركيبة والمكونات والمصنّع والملصقات وبيانات التوريد.",
    "step3Title": "التصنيف والمتطلبات التنظيمية",
    "step3Text": "تحديد فئة كل منتج واستكمال التسجيل أو الموافقات المطلوبة قبل البيع.",
    "step4Title": "SSM والتشغيل",
    "step4Text": "تحديد الكيان التجاري المناسب والحساب والموردين وسياسات العملاء والسجلات التشغيلية.",
    "step5Title": "الإطلاق الرسمي",
    "step5Text": "استبدال التصورات بالمنتجات الحقيقية وتفعيل البيع فقط بعد تأكيد المتطلبات الأساسية.",
    "statusEyebrow": "الوضع الحالي",
    "statusTitle": "غير مطروح للبيع حالياً.",
    "statusText": "TGPU Naturals ما زالت في مرحلة التطوير. التصورات المعروضة لا تمثل العبوة النهائية ولا تُعرض على أنها منتجات مسجلة. سنحدّث المعلومات بعد تأكيد وضع المنتجات وتصنيفها والوثائق ذات الصلة.",
    "faqTitle": "أسئلة قد تطرحها العائلة والعملاء مستقبلاً.",
    "faq1q": "هل يمكنني الطلب الآن؟",
    "faq1a": "ليس عبر هذا الموقع حالياً. نحن نعيد تنظيم المنتجات ونتحقق أولاً من المتطلبات التنظيمية.",
    "faq2q": "هل هذه الصور حقيقية؟",
    "faq2a": "لا. إنها تصورات أولية تساعد عائلتنا على تصور اتجاه العلامة، وستحل محلها الصور الحقيقية لاحقاً.",
    "faq3q": "هل تقدم TGPU Naturals نصائح طبية؟",
    "faq3a": "لا. يقدم الموقع معلومات تعليمية عامة ولا يغني عن الاستشارة الصحية المهنية.",
    "faq4q": "كيف أتابع التطورات؟",
    "faq4a": "تواصل معنا عبر واتساب وأخبرنا أنك ترغب في متابعة تحديثات TGPU Naturals.",
    "contactEyebrow": "نمُ معاً",
    "contactTitle": "استفسارات المنتجات / تواصل معنا",
    "contactText": "للمعلومات والاستفسارات فقط. المنتجات غير مطروحة للبيع حالياً.",
    "contactBtn": "واتساب جنتي",
    "contactPerson": "استفسارات المنتجات: MOE",
    "footerText": "الإنسان · الطبيعة · العائلة · غد أكثر إشراقاً",
    "educationShort": "التعليم",
    "heroSignature": "عائلات سعيدة،\nوغد أكثر إشراقاً",
    "brandTagline": "قيم العائلة · عافية من الطبيعة · غد أكثر إشراقاً",
    "productsSubtitle": "مكونات تقليدية لرحلة العافية اليوم",
    "storySignature": "خطوات صغيرة،\nوأثر يدوم",
    "heritageSignature": "إرثنا،\nعائلتنا،\nغدنا",
    "footerSignature": "العافية اليوم،\nوعائلات أكثر تماسكاً غداً",
    "learnSummary": "دليل المكونات ورحلتنا والأسئلة",
    "menuOpen": "فتح قائمة التنقل",
    "menuClose": "إغلاق قائمة التنقل",
    "switchLabel": "استكشف TGPU Legacy",
    "skip": "انتقل إلى المحتوى",
    "sourceLabel": "مرجع نباتي: كيو للعلوم",
    "artNote": "مشاهد العائلة والتراث توضيحية. صور الكركم الأسود وساشا إنشي محسّنة استناداً إلى العبوات الفعلية، بينما تظل صورة تونغكات علي تصوراً مبدئياً.",
    "copyright": "TGPU Legacy · TGPU Naturals",
    "metaDescription": "تعرّف على TGPU Naturals: إرث عائلي ومعلومات واضحة عن الكركم الأسود وتونغكات علي وساشا إنشي. عبوات تصورية وللاستفسار فقط.",
    "heroAlt": "مشهد توضيحي لعائلة ملايوية تتأمل جبالاً ضبابية من شرفة خشبية.",
    "kunyitAlt": "صورة محسّنة لمنتج الكركم الأسود استناداً إلى الزجاجة والعبوة الفعلية لدى العائلة.",
    "tongkatAlt": "تصور زجاجة تونغكات علي الخضراء بغطاء ذهبي مع جذور وأوراق.",
    "sachiAlt": "صورة محسّنة لمنتج ساشا إنشي استناداً إلى الزجاجة والعبوة الفعلية لدى العائلة."
  }
};
'use strict';
const languages=['ms','en','ar'];
const educationPages={ms:'../',en:'../en.html',ar:'../ar.html'};
const whatsappMessages={ms:'Assalamualaikum MOE, saya ingin bertanya tentang produk TGPU Naturals.',en:'Assalamualaikum MOE, I would like to ask about TGPU Naturals products.',ar:'السلام عليكم MOE، أود الاستفسار عن منتجات TGPU Naturals.'};
const toggle=document.getElementById('menuToggle'),nav=document.getElementById('nav');
let currentLanguage='ms';
function closeMenu(focus=false){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label',translations[currentLanguage].menuOpen);if(focus)toggle.focus();}
function setLanguage(candidate,updateUrl=false){
 const lang=languages.includes(candidate)?candidate:'ms',dict=translations[lang];currentLanguage=lang;
 document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
 document.querySelectorAll('[data-i18n]').forEach(el=>{if(Object.hasOwn(dict,el.dataset.i18n))el.textContent=dict[el.dataset.i18n]});
 document.querySelectorAll('[data-i18n-alt]').forEach(el=>el.alt=dict[el.dataset.i18nAlt]);
 document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',dict[el.dataset.i18nAria]));
 document.querySelectorAll('.lang').forEach(el=>{const active=el.dataset.lang===lang;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));const u=new URL(location.href);u.searchParams.set('lang',el.dataset.lang);el.href=u.pathname+u.search+u.hash;});
 document.querySelectorAll('[data-education]').forEach(el=>el.href=educationPages[lang]);
 document.getElementById('whatsappLink').href='https://wa.me/60126413812?text='+encodeURIComponent(whatsappMessages[lang]);
 document.querySelector('meta[name="description"]').content=dict.metaDescription;document.querySelector('meta[property="og:description"]').content=dict.metaDescription;
 const canonical='https://mamduhsaffin.github.io/tgpu-legacy/wellness/'+(lang==='ms'?'':'?lang='+lang);
 document.querySelector('link[rel="canonical"]').href=canonical;document.querySelector('meta[property="og:url"]').content=canonical;
 document.querySelector('#branchSwitch>summary').setAttribute('aria-label',dict.switchLabel);nav.setAttribute('aria-label',dict.menuOpen);document.querySelector('.footer-links').setAttribute('aria-label',dict.navHome+' · '+dict.navContact);closeMenu();
 try{localStorage.setItem('tgpuNaturalsLang',lang)}catch{}
 if(updateUrl){const u=new URL(location.href);u.searchParams.set('lang',lang);history.pushState({lang},'',u.pathname+u.search+u.hash);}
}
function languageFromUrl(){const requested=new URLSearchParams(location.search).get('lang');if(requested!==null)return languages.includes(requested)?requested:'ms';try{const saved=localStorage.getItem('tgpuNaturalsLang');return languages.includes(saved)?saved:'ms'}catch{return 'ms'}}
document.querySelectorAll('.lang').forEach(link=>{link.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();setLanguage(link.dataset.lang,true)});link.addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();link.click()}})});
setLanguage(languageFromUrl());
toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',translations[currentLanguage][open?'menuClose':'menuOpen']);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(nav.classList.contains('open'))closeMenu(true);const branch=document.getElementById('branchSwitch');if(branch.open){branch.open=false;branch.querySelector('summary').focus()}}});
document.addEventListener('click',e=>{if(!e.target.closest('.nav-shell'))closeMenu();const branch=document.getElementById('branchSwitch');if(!branch.contains(e.target))branch.open=false;});
function revealAnchor(hash,scroll=true){let id;try{id=decodeURIComponent(hash.slice(1))}catch{return}const target=document.getElementById(id);if(!target)return;let p=target;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement}if(scroll)requestAnimationFrame(()=>{target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});if(target.matches('[tabindex]'))target.focus({preventScroll:true})});}
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',()=>{closeMenu();document.getElementById('branchSwitch').open=false;revealAnchor(link.hash,false)}));
window.addEventListener('hashchange',()=>revealAnchor(location.hash));window.addEventListener('popstate',()=>{setLanguage(languageFromUrl());revealAnchor(location.hash)});if(location.hash)revealAnchor(location.hash);
matchMedia('(min-width: 701px)').addEventListener('change',()=>closeMenu());
if('IntersectionObserver'in window){const links=[...nav.querySelectorAll('a')];const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)links.forEach(l=>{const active=l.hash==='#'+e.target.id;l.classList.toggle('is-current',active);if(active)l.setAttribute('aria-current','location');else l.removeAttribute('aria-current')})})},{rootMargin:'-10% 0px -65% 0px'});document.querySelectorAll('#home,#products,#story,#learn,#contact').forEach(s=>obs.observe(s));}

